### ISSUE TITLE
Inaccurate lower bound on `base`

### ISSUE THREAD

**Issue by hvr** [chessai/dura#1]
As can be seen at https://matrix.hackage.haskell.org/package/dura@1555427913 the release `dura-0.1` fails to build with `base-4.10.1.0` (despite the advertised `base >= 4.10.1.0 && < 4.13` support):

```
Configuring library for dura-0.1..
Preprocessing library for dura-0.1..
Building library for dura-0.1..
[1 of 1] Compiling Dura             ( src/Dura.hs, /tmp/matrix-worker/1555428041/dist-newstyle/build/x86_64-linux/ghc-8.2.2/dura-0.1/build/Dura.o )

src/Dura.hs:170:34: error:
    • Variable not in scope: (<>) :: [Char] -> String -> String
    • Perhaps you meant one of these:
        ‘</>’ (imported from System.FilePath),
        ‘<$>’ (imported from Prelude), ‘*>’ (imported from Prelude)
    |
170 |   throwErrnoIfMinus1 ("fsync - " <> name) $
    |                                  ^^

src/Dura.hs:253:23: error:
    • Variable not in scope: (<>) :: [Char] -> FilePath -> t0
    • Perhaps you meant one of these:
        ‘</>’ (imported from System.FilePath),
        ‘<$>’ (imported from Prelude), ‘*>’ (imported from Prelude)
    |
253 |     tmpFilename = "." <> filename <> ".tmp"
    |                       ^^

src/Dura.hs:253:35: error:
    • Variable not in scope: (<>) :: t0 -> [Char] -> t
    • Perhaps you meant one of these:
        ‘</>’ (imported from System.FilePath),
        ‘<$>’ (imported from Prelude), ‘*>’ (imported from Prelude)
    |
253 |     tmpFilename = "." <> filename <> ".tmp"
    |                                   ^^
```

There's no immediate action needed on your part as I've already fixed up the metadata for the affected release (see https://hackage.haskell.org/package/dura-0.1/revisions/) and the resulting build-report can be observed at

https://matrix.hackage.haskell.org/package/dura

**Comment by chessai** [comment]
Apologies, and thanks for the fix.
